---
title: "VivaxModelR: developer doc"
author: "Clara Champagne"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{VivaxModelRdevdoc}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---
    
This document explains the structure of the various functions contained in the package.
These functions are provided in the **R** folder.

The model code, i.e. containing the definition of the ODEs, and formulae for reproduction numbers, equilibrium relationships and transmission rate calibration are provided in the following scripts:
    
- **VivaxFunctions.R** for the models without delayed access to treatment, without RCD and without MDA. 
- **VivaxFunctionsDelays.R** for the models with delayed access to treatment, without RCD and without MDA.
- **VivaxFunctionsRCD.R** for the models with RCD (with and without delayed access to treatment). 
- **VivaxFunctionsDelays.R** for the models with MDA (with and without delayed access to treatment). 


Wrapper functions to apply the model to a full dataset in which each row corresponds to a different setting are available in the following scripts:
    
- **CalculateFromData.R** for the models without delayed access to treatment(with and without MDA and RCD). Contains both calibration and forward simulation.
- **CalculateFromDataDelay.R** for the models with delayed access to treatment (with and without MDA and RCD). Contains both calibration and forward simulation.
- **CalculateFromDataRCD.R** for the calibration with RCD at baseline

Finally, high level wrapper functions are available in **simulate_interventions.R** and auxiliary functions in **aux_functions**.


