on:
  push:
    branches: [sto]
  pull_request:
    branches: [sto]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: covr

      - name: Test coverage
        run: covr::package_coverage()
        shell: Rscript {0}

      - name: Generate code coverage
        run: |
          set -x
          R -e 'covr::package_coverage()' &> out.txt
          total=$(grep "Coverage: " out.txt | grep -oP "(\d+\.\d+)")
          if (( $(echo "$total <= 30" | bc -l) )) ; then
            COLOR=red
          elif (( $(echo "$total > 80" | bc -l) )); then
            COLOR=green
          else
            COLOR=orange
          fi
          echo "TOTAL=$(echo "$total"%)" >> $GITHUB_ENV
          echo "COLOR=$(echo "$COLOR")" >> $GITHUB_ENV
      - name: Create code coverage badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: f66fda014589a897f852edc85f4059fc
          filename: vivax.json
          label: coverage
          message: ${{ env.TOTAL }}
          color: ${{ env.COLOR }}
          style: flat-square
